### ISSUE TITLE
Parse error with coordinates '51.48, 0'

### ISSUE THREAD

**Issue by sytolk** [ianengelbrecht/geo-coordinates-parser#2]
` Uncaught Error: invalid coordinates format`

**Comment by ianengelbrecht** [comment]
Thanks for the alert Stanimir, this is expected behavior. The parser expects coordinates to be 'balanced', ie same format for lat and long. So it has to be 0.0 for longitude. It does this for error checking coordinates. In this case also 51.48 is treated as degrees and minutes, not decimal degrees. So it's wanting zero degrees, zero minutes on the longitude side also. I hope that helps.

**Comment by sytolk** [comment]
Thanks for the explanation Ian. Its appears that I cannot use this parser for formatting && validation of user input lat lng data. Maybe convert() can be splitted to convertLat('51.48') and convertLng('0'). I cannot mix different Lat and Lng formatting now like: '40° 26.7717, 51.48'

**Comment by ianengelbrecht** [comment]
What I suggest is to join the two values with a comma separator from your form inputs and then test with the convert function in the background. You can add a debounce too allow the user some time to type. Add a warning colour to the inputs while the function still throws, and remove when a successfully converted value for both lat and long is present. Check it out here for how we’ve used it: http://www.baboonspideratlas.co.za/contribute/upload-the-record.

**Comment by sytolk** [comment]
Yes I can but this kind of form is not user friendly :) there are so much not successfully converted values: '42 27', '42.1 27.2' but actially this is valid coordinates.

**Comment by ianengelbrecht** [comment]
Okay, my apologies that this can't help you then.

**Comment by nimmolo** [comment]
> Yes I can but this kind of form is not user friendly :) there are so much not successfully converted values: '42 27', '42.1 27.2' but actially this is valid coordinates.

@sytolk This is what i'm trying to do too. Did you find a library that can handle random user-input formats like that?

@ianengelbrecht Thank you for this repo. In my case, i'm also dealing with human-entered data for geo-coordinates that may not be the same format, for example if the user tries to manually tweak the input values after validation.

**Comment by ianengelbrecht** [comment]
@sytolk and @nimmolo, in your code that handles the onupdate event for your form text field for the coordinates, do something like the following (`coordsString` is the input value): 

```
const coordsParts = coordsString.split(/\s,;\//) //split coords on a range of possible separators

//test that each is a valid number
try {

    if (coordsParts.length != 2) {
        // handle invalid user input
    }

    const latitude = Number(coordsParts[0]) //this or the next line will throw if invalid number
    const longitude = Number(coordsParts[1])
    
    //test that  each is valid coordinate value
    if (Math.abs(latitude >= 90) || Math.abs(longitude >= 180)) {
       //do something to handle invalid coordinates 
    }

    // do something here with latitude and longitude

}
catch {
    try {
        const converted = convert(coordsString)
        //do something here with converted coords
    }
    catch(err) {
        //do something to handle invalid coordinates
    }
}
```

Note that `convert` will treat 51.48 as degrees and minutes, as documented. The code above enables you to short circuit this behaviour and treat it as decimal degrees, which seems to be what you want. This code does not require any changes to the UI, only a single text input field for the coordinates.

**Comment by nimmolo** [comment]
@ianengelbrecht Thanks for taking the time to write this out! 

I don't know why I didn't think of breaking up the inputs and testing them separately like this. My form has separate inputs for lat and lng. Oh - I know. At first i was distracted by the fact they had to be joined to be converted, but using this I can test if one or both are already decimals. 

However, the situation i'd like to deal with is separate lat/lng conversions. This could arise in the UI for example if the user's first coordinates have been converted, and the results are now both decimal, but the user decides they are not as desired. 

Then if the user tries to "correct" or tweak only the `lat` using "human-readable" notation, the lat/lng "types" (as a pair) are mismatched because the converted, unaltered `lng` is still decimal, and the joined "lat lng" string will not be convertible. (Of course, the user could clear the form and re-input, but...)

If there were a method in the library to call to convert _only_ the lat, or _only_ the lng, I could use that to try to convert the value of whichever input is `NaN`, and leave the input which is a valid number/decimal alone. 

I checked the library and it doesn't seem like there are these methods, though. I'm trying to think of a refactor to suggest, that would make separate `convertLat`/`convertLng` methods available. It seems like it would require [splitting the regexes](https://stackoverflow.com/a/9213478/3357635).

**Comment by nimmolo** [comment]
Comment edited above - please let me know if you'd be open to a PR to add `convertLat`/`convertLng` methods, and i'll work on it :).

**Comment by ianengelbrecht** [comment]
Thanks for the explanation of your use case @nimmolo. I'm a bit conflicted about the possibility of adding `convertLat/convertLng` because the requirement of equal formats is of primary importance in the conversion function. You'll see its the first thing that gets checked after the regex match. If that check passes then the script does various other things like cleaning up symbols, etc, which depend on that check passing. 

Another possible way to solve your problem would be to display the converted coordinates to the user separately to the input/s (if you have the option to do so). Please play around at https://georeftraining.nscf.org.za, you can drop any coordinates in there and it displays the converted decimal coords below the input. Don't worry about breaking anything on georeftraining, it's not being used at present. Another option would be to store the original input strings and put them back in the inputs when they get focus again, so the user edits their original input values, rather than a converted version of those values (which could be confusing). Just some ideas.
