### ISSUE TITLE
Decimal coordinates are not correctly parsed

### ISSUE THREAD

**Issue by reskume** [ianengelbrecht/geo-coordinates-parser#20]
The handling of parsed decimal coordinates is a bit odd. Those coordinates are parsed correctly:

12.333 56.777

But the parsing fails with "invalid coordinates format" for although valid coordinates:

12.33 56.77
12.3 56.7
12 56

**Comment by ianengelbrecht** [comment]
Yes this comes up repeatedly (see closed issues) but it is intentional behaviour. 

In several cases people record degrees and minutes as 12.33 56.56, using a decimal to separate the degrees and minutes. The default behaviour is to treat these as degrees and minutes, therefore 12.33 56.77 doesn't parse because we can't have 77 minutes. 

The overall reasoning is that if we get decimal coordinates with less than three decimal places then there's probably an error in the coordinates (even though they are technically valid). If you want to treat those as valid your particular use case then rather parse them from the string in your own code before sending the string to convert. 

There is a note about this, marked CAUTION, in the documentation. 

Closing...
