### ISSUE TITLE
Uncaught Error: invalid coordinates format

### ISSUE THREAD

**Issue by luoxiao-supermap** [ianengelbrecht/geo-coordinates-parser#6]
v1.5.7   
When parsing integers the lib throws a  Uncaught Error: invalid coordinates format
convert("10,10")
![image](https://user-images.githubusercontent.com/97505033/182305540-c163c087-de35-43e9-8ed1-60c9aa0f1e07.png)

**Comment by ianengelbrecht** [comment]
Yes this is correct behaviour. The README indicates that it will throw for integer coordinates. This is because it is highly unlikely to have coordinates 10, 10 in any real application, even though they are technically valid coordinates. The reason for throwing is so that unlikely cases like this can be detected and handled appropriately. If your application needs to accept coordinates like this, then use your own code to detect them before they go to convert(). convert() should also always be inside try...catch.
